INSERT INTO productos(id_producto,nombre_producto,nombre_proveedor,codigo_barra,tipo_producto,peso_neto,unidad_peso_neto,desripcion_producto) VALUES (1,'Oreo','Mondelez',7622201693091, 'Galletas', 108, 'Gramos', 'Doble galleta sabor chocolate a chocolate con crema sabor a vainilla');
INSERT INTO productos(id_producto,nombre_producto,nombre_proveedor,codigo_barra,tipo_producto,peso_neto,unidad_peso_neto,desripcion_producto) VALUES (2,'Maravilla','Mackay',7613039496275, 'Galletas', 120, 'Gramos', 'Galleta sabor vainilla');
INSERT INTO productos(id_producto,nombre_producto,nombre_proveedor,codigo_barra,tipo_producto,peso_neto,unidad_peso_neto,desripcion_producto) VALUES (3,'Pepsi','CCU',7801620017552, 'Bebidas', 3, 'Litros', 'Bebida fantasia');
INSERT INTO productos(id_producto,nombre_producto,nombre_proveedor,codigo_barra,tipo_producto,peso_neto,unidad_peso_neto,desripcion_producto) VALUES (4,'Benedictino sin gas','Coca Cola',782820443301, 'Bebidas', 3, 'Litros', 'Agua natural sin gas');
INSERT INTO productos(id_producto,nombre_producto,nombre_proveedor,codigo_barra,tipo_producto,peso_neto,unidad_peso_neto,desripcion_producto) VALUES (5,'Benedictino gasificada','Coca Cola',7802820443356, 'Bebidas', 3, 'Litros', 'Agua natural gasificada');
INSERT INTO productos(id_producto,nombre_producto,nombre_proveedor,codigo_barra,tipo_producto,peso_neto,unidad_peso_neto,desripcion_producto) VALUES (6,'Ron Dominicano','Barceló',7461323129503, 'Alcoholes', 1, 'Litros', 'Ron Añejado');
INSERT INTO productos(id_producto,nombre_producto,nombre_proveedor,codigo_barra,tipo_producto,peso_neto,unidad_peso_neto,desripcion_producto) VALUES (7,'Jabon Liquido Aceite Coco y Jazmin','Ballerina',7804920003065, 'Jabones', 750, 'Mililitros', 'Jabon Liquido');
INSERT INTO productos(id_producto,nombre_producto,nombre_proveedor,codigo_barra,tipo_producto,peso_neto,unidad_peso_neto,desripcion_producto) VALUES (8,'Jabon Liquido Humectante Yoghurt Arandonos','Ballerina',7804920012166, 'Jabones', 750, 'Mililitros', 'Jabon Liquido');
INSERT INTO productos(id_producto,nombre_producto,nombre_proveedor,codigo_barra,tipo_producto,peso_neto,unidad_peso_neto,desripcion_producto) VALUES (9,'Porotitos de Caramelo','Merello',7802247530356, 'Caramelos', 90, 'Gramos', 'Porotitos de caramelo');
INSERT INTO productos(id_producto,nombre_producto,nombre_proveedor,codigo_barra,tipo_producto,peso_neto,unidad_peso_neto,desripcion_producto) VALUES (10,'Limpiado Multiusos','Homecare',7807910029946, 'Limpieza', 500, 'Mililitros', 'Limpiador multiuso');
INSERT INTO productos(id_producto,nombre_producto,nombre_proveedor,codigo_barra,tipo_producto,peso_neto,unidad_peso_neto,desripcion_producto) VALUES (11,'Durazno en cubitos','Huasil',7801305002057, 'Comida', 380, 'Gramos', 'Postre durazno en cubitos');
INSERT INTO productos(id_producto,nombre_producto,nombre_proveedor,codigo_barra,tipo_producto,peso_neto,unidad_peso_neto,desripcion_producto) VALUES (12,'Limpiador multiespacios','Homecare',7807910029847, 'Limpieza', 1800, 'Mililitros', 'Limpiador de pisos aromaticos');
INSERT INTO productos(id_producto,nombre_producto,nombre_proveedor,codigo_barra,tipo_producto,peso_neto,unidad_peso_neto,desripcion_producto) VALUES (13,'Insectisida Mata arañas','Raid Max',7790520009234, 'Insectisidas', 339, 'Gramos', 'Insectisida multiuso');
INSERT INTO productos(id_producto,nombre_producto,nombre_proveedor,codigo_barra,tipo_producto,peso_neto,unidad_peso_neto,desripcion_producto) VALUES (14,'Vino Reserva Merlot','Carmen', 7804335002646, 'Alcoholes', 750, 'Mililitros', 'Alcoholes Vino');

INSERT INTO empresa(id_empresa, rut_empresa, nombre_empresa, direccion_empresa, fono_empresa) VALUES (1, '18.221.431-5', 'QuatroSphere', 'Avenida siempre viva 123', 967453291);

INSERT INTO usuario(id_user, email_user, password, id_empresa) VALUES (1,'ni.caviedes@duocuc.cl', 'hola123', 1);
INSERT INTO usuario(id_user, email_user, password, id_empresa) VALUES (2,'dav.rubio@duocuc.cl', 'hola123', 1);
INSERT INTO usuario(id_user, email_user, password) VALUES (3,'s.plazae@duocuc.cl', 'hola123');
INSERT INTO usuario(id_user, email_user, password) VALUES (4,'j.escobar@duocuc.cl', 'hola123');

INSERT INTO inventario_comercios(id_inv, quantity_prods, unit_price_prod, id_prod, nombre_producto, codigo_barra, tipo_producto, peso_neto, unidad_peso_neto, id_empresa) VALUES (1, 15, 430, 1, 'Oreo', 7622201693091, 'Galletas', 108, 'Gramos', 1);
INSERT INTO inventario_comercios(id_inv, quantity_prods, unit_price_prod, id_prod, nombre_producto, codigo_barra, tipo_producto, peso_neto, unidad_peso_neto, id_empresa) VALUES (3, 6, 3100, 3, 'Pepsi', 7801620017552, 'Bebidas', 3, 'Litros', 1);
INSERT INTO inventario_comercios(id_inv, quantity_prods, unit_price_prod, id_prod, nombre_producto, codigo_barra, tipo_producto, peso_neto, unidad_peso_neto, id_empresa) VALUES (4, 9, 2099, 4, 'Benedictino sin gas', 782820443301, 'Bebidas', 3, 'Litros', 1);
INSERT INTO inventario_comercios(id_inv, quantity_prods, unit_price_prod, id_prod, nombre_producto, codigo_barra, tipo_producto, peso_neto, unidad_peso_neto, id_empresa) VALUES (7, 4, 1780, 7, 'Jabon Liquido Aceite Coco y Jazmin', 7804920003065, 'Jabones', 750, 'Mililitros', 1);
INSERT INTO inventario_comercios(id_inv, quantity_prods, unit_price_prod, id_prod, nombre_producto, codigo_barra, tipo_producto, peso_neto, unidad_peso_neto, id_empresa) VALUES (11, 7, 690, 11, 'Durazno en cubitos', 7801305002057, 'Comida', 380, 'Gramos', 1);