eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8083/eureka/

server:
  port: 8080

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: stores
          uri: http://localhost:8090
          predicates:
            - Path=/api/priv/store/**
      routes:
        - id: stores
          uri: http://localhost:8090
          predicates:
            - Path=/api/priv/store/**