server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8083/eureka/

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: stores
          uri: http://localhost:8090
          predicates:
            - Path=/api/priv/store/**
          filters:
            - AuthenticationFilter
        - id: apipublic
          uri: http://localhost:8094
          predicates:
            - Path=/api/public/**
        - id: authentication
          uri: http://localhost:8098
          predicates:
            - Path=/api/auth/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowCredentials: true 
            maxAge: 3600 
            allowedHeaders:
              - AUTHORIZATION
              - CONTENT_TYPE
              - ACCEPT
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
