server:
  port: 8094
  servlet:
    context-path: /api/public

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka/

spring:
  application:
    name: apipublic
  datasource:
    url: jdbc:mysql://localhost:3308/store_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: store-microservice
    password: sT0r3-m1sv3_Db
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect